//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BusinessOwners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_BusinessOwners()
        {
            this.tb_BusinessApplications = new HashSet<tb_BusinessApplications>();
            this.tb_Directors = new HashSet<tb_Directors>();
        }
    
        public int BusinessID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Office_Phone { get; set; }
        public string Business_Description { get; set; }
        public Nullable<System.DateTime> DateOfCorporation { get; set; }
        public string IncorporationNo { get; set; }
        public string AvgMonthlyIncome { get; set; }
        public string AvgMonthlyExpensis { get; set; }
        public string AvgMonthlyTax { get; set; }
        public Nullable<int> BusinessCatID { get; set; }
        public string CaCDocument { get; set; }
        public string Logo { get; set; }
        public string AccountNo { get; set; }
        public string SortCode { get; set; }
        public Nullable<int> BankID { get; set; }
        public string AccountName { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tb_Banks tb_Banks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BusinessApplications> tb_BusinessApplications { get; set; }
        public virtual tb_BusinessCategory tb_BusinessCategory { get; set; }
        public virtual tb_Role tb_Role { get; set; }
        public virtual tb_Users tb_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Directors> tb_Directors { get; set; }
    }
}
