//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Beneficiaries
    {
        public int BeneficiaryID { get; set; }
        public Nullable<int> InvestorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Relationship { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> BankID { get; set; }
        public string SortCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tb_Banks tb_Banks { get; set; }
        public virtual tb_Investors tb_Investors { get; set; }
    }
}
