//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Disbursements
    {
        public int DisbursmentID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string AmountDisbursed { get; set; }
        public string AmountRemainig { get; set; }
        public string AmountAppliedFor { get; set; }
        public Nullable<System.DateTime> DisbursementDate { get; set; }
        public string DisbursementComment { get; set; }
        public string Status { get; set; }
    
        public virtual tb_BusinessApplications tb_BusinessApplications { get; set; }
    }
}
