//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Directors
    {
        public int DirectorID { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public string Dir_FullName { get; set; }
        public string Dir_Email { get; set; }
        public string Dir_Phone { get; set; }
        public string Dir_Means_of_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tb_BusinessOwners tb_BusinessOwners { get; set; }
    }
}
