//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Guarantors
    {
        public int GurantorID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string GuarantorFirstName { get; set; }
        public string GuarantorLastName { get; set; }
        public string GuarantorEmail { get; set; }
        public string GuarantorPhoneNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tb_BusinessApplications tb_BusinessApplications { get; set; }
    }
}
