//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Investors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Investors()
        {
            this.tb_Beneficiaries = new HashSet<tb_Beneficiaries>();
            this.tb_Investments = new HashSet<tb_Investments>();
        }
    
        public int InvestorID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> BankID { get; set; }
        public string SortCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tb_Banks tb_Banks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Beneficiaries> tb_Beneficiaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Investments> tb_Investments { get; set; }
        public virtual tb_Role tb_Role { get; set; }
        public virtual tb_Users tb_Users { get; set; }
    }
}
