//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InvestmentPackages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_InvestmentPackages()
        {
            this.tb_Investments = new HashSet<tb_Investments>();
        }
    
        public int InvestmentPackageID { get; set; }
        public string PackageName { get; set; }
        public string MinInvestAmt { get; set; }
        public string MaxInvAmt { get; set; }
        public string MinInvestmentDuration { get; set; }
        public string InterestPerMonth { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Investments> tb_Investments { get; set; }
    }
}
