//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Investments
    {
        public int InvestmentID { get; set; }
        public Nullable<int> InvestorID { get; set; }
        public Nullable<int> InvestmentPackageID { get; set; }
        public string InvestmentAmt { get; set; }
        public Nullable<System.DateTime> InvestmentDate { get; set; }
        public Nullable<System.DateTime> ExpectedMaturityDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tb_InvestmentPackages tb_InvestmentPackages { get; set; }
        public virtual tb_Investors tb_Investors { get; set; }
    }
}
