//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Repayments
    {
        public int RepaymentID { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<System.DateTime> RepaymentDate { get; set; }
        public string CurrentRepayment { get; set; }
        public string TotalRepaid { get; set; }
        public string AmountRemaining { get; set; }
        public string TotalMoney { get; set; }
        public Nullable<System.DateTime> ExpectedRepaymentEndDate { get; set; }
        public string RepaymentComment { get; set; }
        public string Status { get; set; }
    
        public virtual tb_BusinessApplications tb_BusinessApplications { get; set; }
    }
}
