//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investis.DomainModel.GeneratedModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Users()
        {
            this.tb_BusinessApplications = new HashSet<tb_BusinessApplications>();
            this.tb_BusinessApplications1 = new HashSet<tb_BusinessApplications>();
        }
    
        public int UserID { get; set; }
        public string Email { get; set; }
        public string HashPassword { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BusinessApplications> tb_BusinessApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BusinessApplications> tb_BusinessApplications1 { get; set; }
        public virtual tb_Investors tb_Investors { get; set; }
        public virtual tb_Role tb_Role { get; set; }
    }
}
